### ISSUE TITLE
Font directory mapping

### ISSUE THREAD

**Issue by MiksLatvis** [m-kro/splitflap#2]
After choosing a font I get this error: (macOS)
<img width="707" alt="Screenshot 2024-03-13 at 20 14 59" src="https://github.com/m-kro/splitflap/assets/786264/27f2c031-e63c-4fb4-88a5-f9b73237cfe4">

**Comment by m-kro** [comment]
I'll try to make it more OS independent. Thanks for posting here the first issue :-)

**Comment by m-kro** [comment]
@MiksLatvis I removed the hard dependance on Windows in the font selection. As I don't have a Mac available, I hope the search paths for fonts are correct:

- /System/Library/Fonts
- /Library/Fonts
